/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "xat.h"
#include <string.h>
#include <unistd.h>

int msleep(long msec) {
    struct timespec ts;
    int res;

    if (msec < 0) {
        return -1;
    }

    ts.tv_sec = msec / 1000;
    ts.tv_nsec = (msec % 1000) * 1000000;

    do {
        res = nanosleep(&ts, &ts);
    } while (res);

    return res;
}

char *readKeyboard(char* user) {

    char *input;
    char c;
    int i = 0;


    input = (char *) malloc(sizeof(char));
    read(0, &c, 1);
    //saltem espais al inici del missatge
    while (c == ' ') {
        read(0, &c, 1);
    }

    while (c != '\n') {
        input[i] = c;
        i++;
        input = (char *) realloc(input, sizeof(char) * (i + 1));
        read(0, &c, 1);
    }

    input[i] = '\0';
    printf("\r");

    return input;
}


void *lectorThread(void *threadInfo) {

    ThreadInfo threadInfoAux = *((ThreadInfo *) threadInfo);
    Xat *xat;
    int getchat_1_arg = 0;

    while (1) {
        xat = getchat_1((void *) &getchat_1_arg, threadInfoAux.clnt);
        if (xat == (Xat *) NULL) {
            clnt_perror(threadInfoAux.clnt, "call failed f2");
        } else {
            for (int i = 0; i < xat->Xat_len; i++) {

                if (strcmp(threadInfoAux.username, xat->Xat_val[i].user) != -32) {
                    printf("%s: %s\n", xat->Xat_val[i].user, xat->Xat_val[i].data);
                }
                getchat_1_arg = getchat_1_arg + strlen(xat->Xat_val[i].user) + strlen(xat->Xat_val[i].data) +
                                1;// + 1 ja que cada strlen ens dona 1 mes i hauria de ser un +3
            }
        }
        msleep(50);
    }
}

void
program_xat_1(char *host, char *user) {
    CLIENT *clnt;
    int *result_1;
    Message writemsg_1_arg;
    char *keyboard;

#ifndef    DEBUG
    clnt = clnt_create(host, PROGRAM_XAT, VERSION_XAT, "udp");
    if (clnt == NULL) {
        clnt_pcreateerror(host);
        exit(1);
    }
#endif    /* DEBUG */

    ThreadInfo threadInfo;
    threadInfo.clnt = clnt;
    threadInfo.username = user;

    pthread_t readThread;
    pthread_create(&readThread, NULL, lectorThread, &threadInfo);

    keyboard = readKeyboard(user);
    writemsg_1_arg.user = user;

    while (strcmp(keyboard, "BYE")) {

        writemsg_1_arg.data = keyboard;
        result_1 = writemsg_1(&writemsg_1_arg, clnt);
        if (result_1 == (void *) NULL) {
            clnt_perror(clnt, "call failed");
        }

        keyboard = readKeyboard(user);
    }

#ifndef    DEBUG
    clnt_destroy(clnt);
#endif     /* DEBUG */
}


int
main(int argc, char *argv[]) {
    char *host;
    char *user;

    if (argc < 3) {
        printf("usage: %s server_host client_username\n", argv[0]);
        exit(1);
    }

    host = argv[1];
    user = argv[2];

    program_xat_1(host, user);

    exit(0);
}
