/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "xat.h"

bool_t
xdr_Message(xdrs, objp)
	XDR *xdrs;
	Message *objp;
{

	if (!xdr_string(xdrs, &objp->data, ~0))
		return (FALSE);
	if (!xdr_string(xdrs, &objp->user, ~0))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_Xat(xdrs, objp)
	XDR *xdrs;
	Xat *objp;
{

	if (!xdr_array(xdrs, (char **)&objp->Xat_val, (u_int *)&objp->Xat_len, ~0, sizeof(Message), (xdrproc_t)xdr_Message))
		return (FALSE);
	return (TRUE);
}
