/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "xat.h"
#include <string.h>

#define BATCH_MESSAGES 200

int *
writemsg_1_svc(Message *argp, struct svc_req *rqstp) {
    static int result;

    FILE *f = fopen("xat.txt", "a");

    fprintf(f, "%s : %s\n", argp->user, argp->data);
    fputs("\0", f);
    fclose(f);

    printf("[SERVER] --- %s : %s\n", argp->user, argp->data);

    return &result;
}

int addMessage(Xat *xat, Message msg) {
    xat->Xat_val = realloc(xat->Xat_val, (xat->Xat_len + 1) * sizeof(Message));
    xat->Xat_val[xat->Xat_len].data = malloc(strlen(msg.data) + 1);
    xat->Xat_val[xat->Xat_len].user = malloc(strlen(msg.user) + 1);

    strcpy(xat->Xat_val[xat->Xat_len].data, msg.data);
    strcpy(xat->Xat_val[xat->Xat_len].user, msg.user);

    xat->Xat_len++;

    return xat->Xat_len;
}

Xat *
getchat_1_svc(int *argp, struct svc_req *rqstp) {
    static Xat result;

    Xat xat;
    xat.Xat_len = 0;
    xat.Xat_val = NULL;

    int nMessages = 0;

    FILE *f = fopen("xat.txt", "r");

    if (f != NULL) {
        fseek(f, *argp, SEEK_SET);

        while (!feof(f) && nMessages < BATCH_MESSAGES) {
            Message m;
            char *p;
            char *line = (char *) malloc(sizeof(char) * 200);

            fgets(line, 200, f);

            if (strlen(line) > 3) {
                p = strtok(line, ":");

                if (p) {
                    m.user = p;
                    p = strtok(NULL, ":");
                }
                if (p) {
                    m.data = p;
                }

                addMessage(&xat, m);
                nMessages++;
            }
            free(line);

        }
        fclose(f);
    }

    result = xat;
    result.Xat_len--;

    return &result;
}
