/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _XAT_H_RPCGEN
#define _XAT_H_RPCGEN

#include <rpc/rpc.h>
#include <stdio.h>
#include <string.h>


#ifdef __cplusplus
extern "C" {
#endif


struct Message {
	char *data;
	char *user;
};
typedef struct Message Message;

typedef struct {
	u_int Xat_len;
	Message *Xat_val;
} Xat;

#define PROGRAM_XAT 0x20000001
#define VERSION_XAT 1

#if defined(__STDC__) || defined(__cplusplus)
#define writeMsg 1
extern  int * writemsg_1(Message *, CLIENT *);
extern  int * writemsg_1_svc(Message *, struct svc_req *);
#define getChat 2
extern  Xat * getchat_1(int *, CLIENT *);
extern  Xat * getchat_1_svc(int *, struct svc_req *);
extern int program_xat_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define writeMsg 1
extern  int * writemsg_1();
extern  int * writemsg_1_svc();
#define getChat 2
extern  Xat * getchat_1();
extern  Xat * getchat_1_svc();
extern int program_xat_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_Message (XDR *, Message*);
extern  bool_t xdr_Xat (XDR *, Xat*);

#else /* K&R C */
extern bool_t xdr_Message ();
extern bool_t xdr_Xat ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_XAT_H_RPCGEN */
