/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "xat.h"


int *
writemsg_1_svc(Message *argp, struct svc_req *rqstp)
{
	static int  result;

	FILE * f = fopen("xat.txt", "a");

	fprintf(f, "%s : %s\n", argp->user, argp->data);

	fclose(f);

	return &result;
}

Xat *
getchat_1_svc(int *argp, struct svc_req *rqstp)
{
	static Xat  result;

	FILE * f = fopen("xat.txt", "r");
	if (f != NULL) {

		result.Xat_len = 0;
		result.Xat_val = (Message *) malloc (sizeof(Message));
		printf("hey \n");
		result.Xat_val[result.Xat_len].data = (char *) malloc (sizeof(char) * 200);
				printf("hey \n");
		fgets(result.Xat_val[result.Xat_len].data, 200, f);
				printf("hey \n");
		result.Xat_val[result.Xat_len].data[strlen(result.Xat_val[result.Xat_len].data) - 1] = '\0';
						printf("hey \n");

		result.Xat_len++;
	}


	return &result;
}
